// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZBIbSROeyWW_-oB13T7M8vWqV2gSZ20k',
    appId: '1:846386062249:android:87725ab02d1ddc0b7b1ab8',
    messagingSenderId: '846386062249',
    projectId: 'fir-g8-5f03c',
    storageBucket: 'fir-g8-5f03c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXl_ayaGhcr4ti1JUJbi3hYZH8Y9vZERw',
    appId: '1:846386062249:ios:fdbd14f6fda89f6d7b1ab8',
    messagingSenderId: '846386062249',
    projectId: 'fir-g8-5f03c',
    storageBucket: 'fir-g8-5f03c.appspot.com',
    iosClientId: '846386062249-c3e8p8ogendliimiqc2m02k5i4cttq6q.apps.googleusercontent.com',
    iosBundleId: 'pe.codigog8.appvotacion',
  );
}
